import { Recipe } from "../RecipeFilters/Types";
import chickenPastaBakeImg from "../../assets/chicken-pasta-bake-cropped.jpg";
import aubergineVeggieChilliImg from "../../assets/aubergine-chilli.jpg";

const unsortedData: Recipe[] = [
  {
    path: "/aubergine-veggie-chilli",
    inspiredBy: "https://www.bbcgoodfood.com/recipes/burnt-aubergine-veggie-chilli",
    image: aubergineVeggieChilliImg,
    imageAlt: "A yellow and red plate with a pile of rice topped with a vegetable chilli.",
    title: "Aubergine Veggie Chilli",
    time: "1 hr 30",
    description: "This warming aubergine chilli is filled with veggies and freezes well.",
    serves: 12,
    ingredients: [
      [4, " aubergines, cut into 2cm chunks"],
      [3, " red/orange/yellow peppers, deseeded and cut into 2cm chunks"],
      [2, " red onions, diced"],
      [6, " medium carrots, diced"],
      [2, " x 400g can green lentils"],
      [2, " x 400g can borlotti beans - don't drain"],
      [2, " x 400g can chopped tomatoes"],
      [6, " tbsp dark soy sauce"],
      [2, " squares dark chocolate"],
      [3, " vegetable stock cubes"],
      [250, "ml water, boiled"],
      [0.5, " tsp chilli flakes or chilli powder"],
      [4, " tsp dried oregano"],
      [4, " tsp ground cumin"],
      [4, " tsp smoked paprika"],
      [2, " tsp ground coriander"],
      [2, " tsp ground cinnamon"],
      [4, " cups rice"],
      [2, " tbsp lime juice"],
      [0, "Salt"],
      [0, "Pepper"],
      [0, "Olive oil"],
    ],
    method: [
      "Preheat the oven to 220°C, gas mark 7. Spread the aubergines and peppers out in a single layer over 1 or 2 roasting tins, drizzle generously with olive oil, salt and pepper, and toss to coat. Spread out again, then roast for 15-20 minutes, until soft.",
      "In a large pan, heat the oil then fry the onion and carrots over a low-medium heat for 15-20 mins until the carrots have softened.",
      "Add the aubergine, peppers, drained lentils, borlotti beans (including the liquid from the can), soy sauce, tomatoes, chocolate, chilli flakes/powder, oregano, cumin, paprika, ground coriander, cinnamon, stock cubes and water.",
      "Bring to the boil, then turn the heat down very low, cover with a lid and cook for 15-30 minutes, depending on your patience level! Stir occasionally.",
      "Remove the lid and simmer over a low-medium heat for 10-15 mins to get a thicker sauce.",
      "Meanwhile, cook the rice according to instructions",
      "Stir lime juice into the chilli, then serve over the rice.",
    ],
    filters: {
      details: {
        type: "main meal",
        base: "rice",
        protein: "beans",
        dish: "chilli",
        cookingMethod: ["hob", "oven"],
      },
      attributes: {
        freezable: true,
        hotWeatherFriendly: false,
        author: "",
      },
      dietaries: {
        dietaryNotes:
          "Make sure the chocolate doesn't contain milk if you want this to be vegan. Remove the soy sauce to make this recipe soy-free",
        dairyFree: true,
        eggFree: true,
        halal: true,
        fishFree: true,
        glutenFree: true,
        kosher: true,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: false,
        pescatarian: true,
        vegetarian: true,
        vegan: true,
      },
    },
  },
  {
    path: "/baked-tortilla-crisps",
    inspiredBy: "https://www.bbc.co.uk/food/recipes/baked_tortilla_crisps_65727",
    image: "https://d1da880v85k5s1.cloudfront.net/8d9kdsuvlw0ss.jpg",
    imageAlt: "Golden, crispy baked tortilla triangles sprinkled with salt",
    title: "Baked tortilla crisps",
    time: "20 mins",
    description:
      "For the forgotten wraps slowly turning hard in the cupboard – transform them into golden, crispy tortilla crisps in minutes! Serve with hummus and salad for lunch, or as a snack with dips.",
    serves: 1,
    ingredients: [
      [1, " wrap"],
      [1, " tsp oil"],
      [0, "Salt"],
    ],
    method: [
      "Preheat the oven to 170C/150C Fan/Gas 3.",
      "Cut the wrap into roughly 5cm/2in-wide strips, then cut each strip at an angle into triangles. Put in a bowl and drizzle over the oil to very lightly coat the triangles.",
      "Transfer to a baking tray in a single layer and lightly sprinkle with salt.",
      "Bake for 5–8 minutes, gently shake the tray, then return to the oven for another 2–4 minutes until golden-brown and crisp. Allow to cool before serving with dips or salad.",
    ],
    filters: {
      attributes: {
        author: "",
        freezable: false,
        hotWeatherFriendly: true,
      },
      details: {
        type: "other",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: true,
        eggFree: true,
        halal: true,
        fishFree: true,
        glutenFree: false,
        kosher: true,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: true,
        vegetarian: true,
        vegan: true,
      },
    },
  },
  {
    path: "/cassoulet",
    inspiredBy:
      "https://www.waitrose.com/ecom/recipe/summer-veg-bacon-cassoulet?srsltid=AfmBOorEAYEGF5ACVVMPyB0U7wzypcdICXb_pp0mLghy4yfruC2lP8Ug",
    image:
      "https://waitrose-prod.scene7.com/is/image/waitroseprod/summer-veg-and-bacon-cassoulet?uuid=cdb282f7-d972-4d21-94e7-9720a19c98d6&$Waitrose-Image-Preset-90$&wid=2400&fit=constrain%2C0",
    imageAlt: "Serving bowl filled with cassoulet - a butter bean based stew",
    title: "Summer veg & bacon cassoulet",
    time: "1 hr 10",
    description:
      "A less heavy take on the traditional French stew, this has all the flavours of a hot summer holiday. Roasting the veg first intensifies the flavour so everything tastes its absolute best.",
    serves: 8,
    ingredients: [
      [2, " aubergines, cut into 2cm chunks"],
      [2, " red or orange peppers, deseeded and cut into 2cm chunks"],
      [100, "ml extra virgin olive oil"],
      [200, "g pack unsmoked bacon lardons"],
      [1, " onion, peeled and finely sliced"],
      [3, " cloves garlic, peeled and crushed"],
      [400, "g cherry tomatoes on the vine, stalks removed"],
      [2, " x 400g can butter beans, drained"],
      [3, " sprigs rosemary"],
      [500, "ml water"],
      [2, " vegetable stock cubes"],
      [1, " handful of basil leaves, to serve"],
      [8, " portions of garlic-rubbed sourdough toast, to serve (optional)"],
      [1, " lemon, cut into wedges, to serve"],
    ],
    method: [
      "Preheat the oven to 220°C, gas mark 7. Spread the aubergines and peppers out in a single layer over 1 or 2 roasting tins, drizzle generously with 5 tbsp oil, season with salt and pepper, then toss to coat. Spread out again and roast for 35-40 minutes, turning once, until golden and caramelised.",
      "Meanwhile, heat 2 tbsp oil in a wide ovenproof shallow casserole and place over a medium-high heat. Fry the lardons for 10 minutes, until crisp and golden, then remove with a slotted spoon, leaving the fat in the pan.",
      "Fry the onion in the fat for 8-10 minutes, stirring often, until softened with a little colour, then add the garlic and fry for 2 minutes more. Set aside until needed.",
      "When the roasted vegetables are ready, add the tomatoes, beans, rosemary, water and stock cubes to the onion pan and bring to a simmer. Add the roasted vegetables, season well, then transfer, uncovered, to the oven. Bake for 20 minutes, until the tops of the vegetables and beans are deep golden and a little crisp. Scatter the cassoulet with the basil, then serve with garlic-rubbed toast, if liked, and lemon wedges for squeezing.",
    ],
    filters: {
      details: {
        type: "main meal",
        base: "served with bread/toast",
        protein: "beans",
        dish: "stew",
        cookingMethod: ["hob", "oven"],
      },
      attributes: {
        freezable: true,
        hotWeatherFriendly: false,
        author: "",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: true,
        eggFree: true,
        halal: true,
        fishFree: true,
        glutenFree: true,
        kosher: true,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: false,
        vegetarian: false,
        vegan: false,
        veganAdjustable: true,
        makeItVegan: {
          instructions: "Removed the bacon",
          veganIngredients: [
            [2, " aubergines, cut into 2cm chunks"],
            [2, " red or orange peppers, deseeded and cut into 2cm chunks"],
            [100, "ml extra virgin olive oil"],
            [1, " onion, peeled and finely sliced"],
            [3, " cloves garlic, peeled and crushed"],
            [400, "g cherry tomatoes on the vine, stalks removed"],
            [2, " x 400g can butter beans, drained"],
            [3, " sprigs rosemary"],
            [500, "ml water"],
            [2, " vegetable stock cubes"],
            [1, " handful of basil leaves, to serve"],
            [8, " portions of garlic-rubbed sourdough toast, to serve (optional)"],
            [1, " lemon, cut into wedges, to serve"],
          ],
          veganMethod: [
            "Preheat the oven to 220°C, gas mark 7. Spread the aubergines and peppers out in a single layer over 1 or 2 roasting tins, drizzle generously with 5 tbsp oil and toss to coat. Spread out again, then season and roast for 35-40 minutes, turning once, until golden and caramelised.",
            "Meanwhile, heat 2 tbsp oil in a wide ovenproof shallow casserole and place over a medium-high heat.",
            "Fry the onion in the oil for 8-10 minutes, stirring often, until softened with a little colour, then add the garlic and fry for 2 minutes more. Set aside until needed.",
            "When the roasted vegetables are ready, add the tomatoes, beans, rosemary, water and stock cubes to the onion pan and bring to a simmer. Add the roasted vegetables, season well, then transfer, uncovered, to the oven. Bake for 20 minutes, until the tops of the vegetables and beans are deep golden and a little crisp. Scatter the cassoulet with the basil, then serve with garlic-rubbed toast, if liked, and lemon wedges for squeezing.",
          ],
        },
      },
    },
  },
  {
    path: "/cherry-tomato-sauce",
    inspiredBy: "https://www.forkknifeswoon.com/quick-roasted-cherry-tomato-sauce/",
    image: "https://d1da880v85k5s1.cloudfront.net/8d9kdsuvlw0ss.jpg",
    imageAlt: "Cherry tomato and onion sauce, with a glossy finish",
    title: "Cherry tomato sauce",
    time: "1 hr",
    description:
      "A simple but effective use of excess cherry tomatoes (or worth buying them for if you haven't the patience for watering the plants for months!). Add pasta for a basic weeknight dinner.",
    serves: 2,
    ingredients: [
      [400, "g cherry tomatoes"],
      [1, " small onion, chopped"],
      [0, "Garlic granules"],
      [0, "Dried basil"],
      [0, "Dried thyme"],
      [0, "Olive oil"],
      [0, "Salt"],
      [0, "Pepper"],
    ],
    method: [
      "Preheat the oven to 200C/180C Fan/Gas 4.",
      "Put the cherry tomatoes into a large bakng tray, add a generous amount of oil and season well with salt and pepper. Cook for around 30-40 mins, until the tomatoes have burst and start shrivelling.",
      "Meanwhile, put some olive oil in a pan on medium heat, then add the chopped onion. Fry for 5 mins until soft.",
      "Add the tomatoes and then add garlic granules, dried basil, dried thyme, salt and pepper as desired.",
      "if cooking pasta, add some cooked pasta water too.",
    ],
    filters: {
      attributes: {
        author: "",
        freezable: true,
        hotWeatherFriendly: false,
      },
      details: {
        type: "other",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: true,
        eggFree: true,
        halal: true,
        fishFree: true,
        glutenFree: true,
        kosher: true,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: true,
        vegetarian: true,
        vegan: true,
      },
    },
  },
  {
    path: "/chicken-pasta-bake",
    inspiredBy: "https://www.bbcgoodfood.com/recipes/chicken-pasta-bake",
    image: chickenPastaBakeImg,
    imageAlt: "Chicken pasta bake topped with golden melted cheese",
    title: "Chicken pasta bake",
    time: "1 hr 15",
    description:
      "Enjoy this gooey cheese and chicken pasta bake for the ultimate weekday family dinner. Serve straight from the dish with a dressed green salad.",
    serves: 9,
    ingredients: [
      [4, " tbsp olive oil"],
      [1, " onion, finely chopped"],
      [2, " tsp garlic granules"],
      [0.25, " tsp chilli flakes"],
      [3, " x 400g passata or chopped tomatoes cans"],
      [2, " tsp dried basil or parsley"],
      [1, " pot of mascarpone"],
      [1, " bag of kale"],
      [1, " x 260g can of sweetcorn"],
      [650, "g diced chicken (or buy chicken breasts and dice at home)"],
      [400, "g penne"],
      [200, "g grated mature cheddar/mozzarella/both"],
      [0, "Salt and pepper"],
      [0, "Small bunch of basil or parsley, finely chopped (optional)"],
    ],
    method: [
      "Heat 2 tbsp of the oil in a big saucepan over a medium heat and fry the onion gently for 10-12 mins. Add the garlic granules and chilli flakes and cook for 1 min. Tip in the tomatoes, add the basil/parsley and season to taste. Simmer uncovered for 20 mins, adding the kale after 10 mins. Then stir through the mascarpone and sweetcorn.",
      "Heat 1 tbsp of oil in a non-stick frying pan. Season the chicken and fry for 5-7 mins or until the chicken is cooked through.",
      "Heat the oven to 220C/200C fan/gas mark 7. Cook the penne following pack instructions. Drain and toss with the remaining oil. Add the pasta and chicken to the sauce and mix well. Then tip into a medium sized ovenproof dish. Top with the cheddar, mozzarella and optional fresh basil/parsley. Bake for 20 mins or until golden brown and bubbling.",
    ],
    filters: {
      details: {
        type: "main meal",
        base: "pasta",
        protein: "chicken",
        dish: "pasta bake",
        cookingMethod: ["hob", "oven"],
      },
      attributes: {
        freezable: true,
        hotWeatherFriendly: false,
        author: "",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: false,
        eggFree: true,
        halal: true,
        fishFree: true,
        glutenFree: true,
        kosher: false,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: false,
        vegetarian: false,
        vegan: false,
        veganAdjustable: false,
      },
    },
  },
  {
    path: "/chicken-caesar-salad-wrap",
    inspiredBy: "",
    image: "https://i.pinimg.com/originals/15/ad/46/15ad46012040bcd7eab776f7d10a24f5.jpg",
    imageAlt:
      "A bowl of tossed chicken, bacon, croutons and lettuce, with a healthy amount of parmesan grated on top",
    title: "Chicken caesar salad wrap",
    time: "1 hr 20",
    description: "",
    serves: 4,

    ingredients: [[2, "hg"]],
    method: [""],
    filters: {
      details: {
        type: "main meal",
        base: "wrap",
        protein: "chicken",
        dish: "salad",
        cookingMethod: ["oven"],
      },
      attributes: {
        freezable: false,
        hotWeatherFriendly: true,
        author: "Barn",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: false,
        eggFree: false,
        halal: true,
        fishFree: true,
        glutenFree: false,
        kosher: false,
        lactoseFree: false,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: false,
        vegetarian: false,
        vegan: false,
        veganAdjustable: false,
      },
    },
  },
  {
    path: "/french-dressing",
    inspiredBy: "https://www.bbcgoodfood.com/howto/guide/10-salad-dressings-you-can-make-minutes",
    image:
      "https://images.immediate.co.uk/production/volatile/sites/30/2016/08/French-dressing-a881090.jpg?quality=90&webp=true&fit=975,649",
    imageAlt:
      "A bowl of yellow salad dressing in a white and blue bowl with a whisk discarded to the side",
    title: "French dressing",
    time: "1 hr 30",
    description:
      "A classic recipe that everyone enjoys, made with oil and vinegar. This is the solid foundation of the salad dressing world.",
    serves: 8,
    ingredients: [
      [1, " tsp Dijon mustard"],
      [2, " tbsp white wine vinegar"],
      [6, " tbsp extra virgin olive oil"],
      [0, "Sugar"],
      [0, "Salt and pepper"],
    ],
    method: [
      "To make, whisk 1 tsp Dijon mustard with 2 tbsp white wine vinegar, 6 tbsp extra virgin olive oil, a pinch of sugar and salt and pepper in a small bowl or shake together in a jam jar.",
    ],
    filters: {
      details: {
        type: "other",
      },
      attributes: {
        freezable: false,
        hotWeatherFriendly: true,
        author: "",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: true,
        eggFree: true,
        halal: true,
        fishFree: true,
        glutenFree: true,
        kosher: true,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: true,
        vegetarian: true,
        vegan: true,
      },
    },
  },
  {
    path: "/gochujang-pasta",
    inspiredBy: "https://www.mealofjoy.com/p/sausage-gochujang-pasta",
    image:
      "https://substackcdn.com/image/fetch/$s_!I9KH!,w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fb65a86b1-15e6-4b19-90ce-74f833391e7f_3024x3442.jpeg",
    imageAlt: "",
    title: "Sausage gochujang pasta",
    time: "50 mins",
    description: "Spicy gochujang and creamy sausage pasta is a match made in heaven.",
    serves: 10,
    ingredients: [
      [1000, "g pasta (rigatoni or any short pasta)"],
      [12, " high-quality sausages (about 320g)"],
      [2, " medium onions"],
      [2, " tsp garlic granules"],
      [5, " tbsp gochujang paste"],
      [400, "ml cream"],
      [2, " tbsp lime juice"],
      [3, " tbsp honey"],
      [50, "g coriander"],
      [50, "g parmesan"],
      [300, "g frozen peas"],
      [0, "Olive oil"],
    ],
    method: [
      "Remove the casing from the sausages and fry them in olive oil in a large pan or casserole dish over medium-high heat. Mash them with a spatula or wooden spoon so they break up, then cook through. Remove from the pan and set aside.",
      "Add more oil, then fry the onion with the garlic granules for 5-10 minutes until softened.",
      "Now add the gochujang, cream, grated parmesan cheese, lime juice, honey. Let it simmer for 3 minutes, then add the sausage pieces back in.",
      "Stir everything well and let it simmer a bit more until it thickens slightly. Season with salt and pepper to taste (if needed - I prefer not to).",
      "Cook the pasta. Once it's al dente, save some of the pasta water then drain it. Add a small ladle of the cooking water to your pan and mix until the sauce becomes glossy. Keep tasting and add more water if needed.",
      "Add the frozen peas, and most of the chopped coriander to the pasta and mix until the peas have defrosted (don't overcook, peas are best fresh).",
      "Serve the pasta with the rest of the parmesan and coriander.",
    ],
    filters: {
      details: {
        type: "main meal",
        base: "pasta",
        protein: "sausage",
        dish: "pasta",
        cookingMethod: ["hob"],
      },
      attributes: {
        freezable: true,
        hotWeatherFriendly: false,
        author: "",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: false,
        eggFree: true,
        halal: false,
        fishFree: true,
        glutenFree: false,
        kosher: false,
        lactoseFree: false,
        nutFree: true,
        shellfishFree: true,
        soyFree: false,
        pescatarian: false,
        vegetarian: false,
        vegan: false,
        veganAdjustable: false,
      },
    },
  },
  {
    path: "/greek-pasta-salad",
    inspiredBy: "https://www.bbc.co.uk/food/recipes/greek_pasta_salad_15496",
    image:
      "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/greek_pasta_salad_15496_16x9.jpg",
    imageAlt:
      "A vibrant Greek pasta salad tossed with cucumbers, quartered cherry tomatoes, crumbled feta, and fresh basil",
    title: "Greek pasta salad",
    time: "40 mins",
    description:
      "This easy pasta salad is packed with Mediterranean flavours. Perfect for lunch or as a barbecue side dish as it keeps really well, so it's ideal to make ahead and keep in the fridge.",
    serves: 1,
    ingredients: [
      [85, "g pasta, such as penne or conchiglie"],
      [0.5, " unwaxed lemon, finely grated zest and juice"],
      [0.2, " red onion, finely chopped"],
      [0.5, " tbsp olive oil, ideally extra virgin"],
      [0.25, " cucumber, peeled and cubed"],
      [100, "g cherry tomatoes, quartered"],
      [15, "g fresh basil, roughly chopped"],
      [60, "g feta, crumbled (optional)"],
      [0, "Handful pitted black olives (optional)"],
      [0, "Salt and freshly ground black pepper"],
    ],
    method: [
      "Cook the pasta in a saucepan of boiling, salted water as per the packet instructions.",
      "Whisk together the lemon zest and juice, red onion, oil and a generous amount of pepper.",
      "Drain the pasta in a colander and run it under a cold tap until cooled.",
      "Stir the dressing, cucumber, tomatoes, basil, feta and olives, if using, into the pasta and serve.",
    ],
    filters: {
      attributes: {
        author: "",
        freezable: false,
        hotWeatherFriendly: true,
      },
      details: {
        type: "main meal",
        base: "pasta",
        protein: "none",
        dish: "salad",
        cookingMethod: ["hob", "no cook"],
      },
      dietaries: {
        dietaryNotes:
          "To ensure this dish is gluten-free, use a certified gluten-free pasta alternative.",
        dairyFree: false,
        eggFree: true,
        halal: false,
        fishFree: true,
        glutenFree: false,
        kosher: false,
        lactoseFree: false,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: true,
        vegetarian: true,
        vegan: false,
        veganAdjustable: true,
        makeItVegan: {
          instructions: "Omitted the feta.",
          veganIngredients: [
            [85, "g pasta, such as penne or conchiglie"],
            [0.5, " unwaxed lemon, finely grated zest and juice"],
            [0.2, " red onion, finely chopped"],
            [0.5, " tbsp olive oil, ideally extra virgin"],
            [0.25, " cucumber, peeled and cubed"],
            [100, "g cherry tomatoes, quartered"],
            [15, "g fresh basil, roughly chopped"],
            [0, "Handful pitted black olives (optional)"],
            [0, "Salt and pepper"],
          ],
          veganMethod: [
            "Cook the pasta in a saucepan of boiling, salted water as per the packet instructions.",
            "Whisk together the lemon zest and juice, red onion, oil and a generous amount of pepper.",
            "Drain the pasta in a colander and run it under a cold tap until cooled.",
            "Stir the dressing, cucumber, tomatoes, basil and olives, if using, into the pasta and serve.",
          ],
        },
      },
    },
  },
  {
    path: "/lamingtons",
    inspiredBy: "https://www.recipetineats.com/classic-lamingtons/",
    image: "https://tse4.mm.bing.net/th/id/OIP.TGz02e3VrwgeVD0g1UzX_wHaJQ?r=0&pid=Api",
    imageAlt:
      "Squares of Australian lamingtons, a sponge cake covered in chocolate and coconut shavings",
    title: "Lamingtons",
    time: "45 mins",
    description:
      "Lamingtons are an Australian cake, which takes a classic sponge, covers it in chocolate and coconut shavings.",
    serves: 12,
    ingredients: [
      [0, "tbc"],
      [200, "g vegan margarine"],
      [150, "g caster sugar"],
      [100, "g soft brown sugar"],
      [1, " teaspoon vanilla extract"],
      [320, "g self-raising flour"],
      [250, "g vegan chocolate chips or vegan dark chocolate chopped up"],
      [0, " Splash plant-based milk"],
    ],
    method: [
      'Preheat your oven to 180°C/160°C Fan. Line an 8x10"/20x25cm tin with baking paper or wipe the tin with the vegan margarine. Letting some hang over the edges allows for easy removal.',
      "In a large bowl, mix together the margarine, caster sugar and brown sugar. Add in the vanilla and mix again.",
      "Next, add all of the flour to the bowl. Mix it in and when it starts to stick together, use your hands to press it into a dough. If the dough is crumbly, add a small splash of plant-based milk to help it stick together. I used about 2 teaspoons.",
      "Once your dough is the right consistency, add in the chocolate chips, saving a handful for the top. Gently fold them in using your hands.",
      "Place the cookie dough into your lined baking tin and press it out to the edges as evenly as you can. Gently press in the remaining chocolate chips.",
      "Bake for 25 minutes or until the top is light golden brown. Leave it in the tin to cool completely.",
      "Once cool, place it in the fridge for 2 hours. This will help it to firm up quicker and prevent the cookie squares from crumbling.",
      "After refrigerating, cut the cookie into 12 equal-sized squares and enjoy!",
    ],
    filters: {
      attributes: {
        author: "",
        freezable: true,
        hotWeatherFriendly: false,
      },
      details: {
        type: "baking",
      },
      dietaries: {
        dietaryNotes:
          "Ensure all chocolate chips and plant-based milk brands used are certified gluten-free/nut-free if catering for strict allergies.",
        dairyFree: true,
        eggFree: true,
        halal: true,
        fishFree: true,
        glutenFree: false,
        kosher: true,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: true,
        vegetarian: true,
        vegan: true,
      },
    },
  },
  {
    path: "/lentil-gnocchi-ragu",
    inspiredBy: "https://www.bbc.co.uk/food/recipes/saucy_lentil_gnocchi_rag_84948",
    image:
      "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/saucy_lentil_gnocchi_rag_84948_16x9.jpg",
    imageAlt: "Serving bowl of lentil gnocchi ragu with basil and parmesan sprinkled on top",
    title: "Saucy lentil gnocchi ragù",
    time: "1 hr 30",
    description:
      "An extremely saucy and comforting ragù-style dish that skips the meat but does not skimp on flavour. Made in one pot, it really couldn't be easier!",
    serves: 8,
    ingredients: [
      [1, " tbsp olive oil"],
      [1, " tsp paprika"],
      [1, " tsp dried oregano"],
      [0.5, " tsp dried red chilli flakes (optional)"],
      [5, " garlic cloves, blended or finely chopped"],
      [1, " onion, blended or finely chopped"],
      [2, " celery sticks, blended or finely chopped"],
      [250, "g chestnut mushrooms, blended or finely chopped"],
      [2, " carrots, peeled and blended or finely chopped"],
      [2, " tbsp tomato purée"],
      [3, " tbsp dark soy sauce"],
      [1, " x 400g tin chopped tomatoes"],
      [1, " vegetable stock cube"],
      [1, " x 400g tin green lentils, drained"],
      [1, " tsp sugar"],
      [2, " x 400g packets fresh gnocchi"],
      [0, "Salt and freshly ground black pepper"],
      [0, "Handful of fresh basil leaves, sliced, to garnish"],
      [0, "Vegetarian hard cheese or dairy-free alternative, finely grated, to serve (optional)"],
    ],
    method: [
      "Heat the oil in a large saucepan. Stir in the paprika, oregano and chilli flakes and fry for 1 minute to infuse the spices.",
      "Add the garlic, onion and celery and cook for a few minutes until softened. Add the mushrooms and cook for 5 minutes to draw out their moisture. Add the carrots and cook for a further 2 minutes.",
      "Mix in the tomato purée and soy sauce.",
      "Pour in the tomatoes. Refill the empty tomato tin with boiling water and the stock cube, stir until dissolved and then pour the stock into the pan. Add the lentils and sugar and mix everything together.",
      "Simmer for around 15 minutes, stirring occasionally, or until it begins to thicken but still remains saucy. Season generously with salt and pepper.",
      "Add the gnocchi directly into the sauce, stir through and cook for a few minutes until soft and ready to eat.",
      "Serve in bowls and garnish with a handful of the basil. Serve with a good sprinkling of the cheese, if using.",
    ],
    filters: {
      details: {
        type: "main meal",
        base: "gnocchi",
        protein: "lentils",
        dish: "ragu",
        cookingMethod: ["hob"],
      },
      attributes: {
        freezable: true,
        hotWeatherFriendly: false,
        author: "",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: true,
        eggFree: true,
        halal: true,
        fishFree: true,
        glutenFree: true,
        kosher: true,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: true,
        vegetarian: true,
        vegan: false,
        veganAdjustable: true,
        makeItVegan: {
          instructions: "Removed the cheese",
          veganIngredients: [
            [1, " tsp paprika"],
            [1, " tsp dried oregano"],
            [0.5, " tsp dried red chilli flakes (optional)"],
            [5, " garlic cloves, blended or finely chopped"],
            [1, " onion, blended or finely chopped"],
            [2, " celery sticks, blended or finely chopped"],
            [250, "g chestnut mushrooms, blended or finely chopped"],
            [2, " carrots, peeled and blended or finely chopped"],
            [2, " tbsp tomato purée"],
            [3, " tbsp dark soy sauce"],
            [1, " x 400g tin chopped tomatoes"],
            [1, " vegetable stock cube"],
            [1, " x 400g tin green lentils, drained"],
            [1, " tsp sugar"],
            [2, " x 400g packets fresh gnocchi"],
            [0, "Salt and freshly ground black pepper"],
            [0, "Handful of fresh basil leaves, sliced, to garnish"],
            [
              0,
              "Vegetarian hard cheese or dairy-free alternative, finely grated, to serve (optional)",
            ],
          ],
          veganMethod: [
            "Heat the oil in a large saucepan. Stir in the paprika, oregano and chilli flakes and fry for 1 minute to infuse the spices.",
            "Add the garlic, onion and celery and cook for a few minutes until softened. Add the mushrooms and cook for 5 minutes to draw out their moisture. Add the carrots and cook for a further 2 minutes.",
            "Mix in the tomato purée and soy sauce.",
            "Pour in the tomatoes. Refill the empty tomato tin with boiling water and the stock cube, stir until dissolved and then pour the stock into the pan. Add the lentils and sugar and mix everything together.",
            "Simmer for around 15 minutes, stirring occasionally, or until it begins to thicken but still remains saucy. Season generously with salt and pepper.",
            "Add the gnocchi directly into the sauce, stir through and cook for a few minutes until soft and ready to eat.",
            "Serve in bowls and garnish with a handful of the basil.",
          ],
        },
      },
    },
  },
  {
    path: "/sausage-bolognese",
    inspiredBy: "https://www.bbc.co.uk/food/recipes/spicy_sausage_pasta_42455",
    image:
      "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/spicy_sausage_pasta_42455_16x9.jpg",
    imageAlt: "",
    title: "Sausage bolognese",
    time: "1 hr 20",
    description: "",
    serves: 4,
    ingredients: [
      [6, " good-quality sausages"],
      [1, " tbsp olive oil"],
      [1, " small onion, finely chopped"],
      [0.5, " tsp dried chilli flakes, according to taste"],
      [400, "g tin chopped tomatoes"],
      [2, " tbsp tomato purée"],
      [150, "ml red wine or water"],
      [0.5, " tsp dried mixed herbs or dried oregano"],
      [275, "g dried spaghetti (or other pasta if freezing)"],
      [0, "Grated parmesan, to serve (optional)"],
      [0, "Handful of fresh basil leaves, to serve (optional)"],
    ],
    method: [
      "Squeeze the sausagemeat out of the skins into a large non-stick frying pan. Add the oil and onion and cook over a medium heat for 10 minutes, or until lightly browned. Use two wooden spoons to break up the sausagemeat into small mince-like pieces as it cooks. Add the chilli flakes and cook for 1 minute more, stirring.",
      "Add the tomatoes, tomato purée, red wine (or water) and oregano. Bring to a gentle simmer and cook for 8–10 minutes, or until the sauce has thickened, stirring regularly.",
      "Meanwhile, fill a large saucepan with water and bring to the boil. Add the pasta to the water and cook for 7–9 minutes (or according to the pack instructions) until tender, stirring occasionally to separate the strands.",
      "Drain the cooked pasta in a colander and return to the saucepan. Tip the spicy sausage sauce into the same pan and toss well together. Serve topped with grated Parmesan and scattered with torn basil leaves.",
    ],
    filters: {
      details: {
        type: "main meal",
        base: "pasta",
        protein: "sausage",
        dish: "bolognese",
        cookingMethod: ["hob"],
      },
      attributes: {
        freezable: true,
        hotWeatherFriendly: false,
        author: "",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: true,
        eggFree: true,
        halal: false,
        fishFree: true,
        glutenFree: false,
        kosher: false,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: false,
        vegetarian: false,
        vegan: false,
        veganAdjustable: false,
      },
    },
  },
  {
    path: "/sausage-courgette-pilaf",
    inspiredBy: "https://www.bbcgoodfoodme.com/recipes/easy-sausage-courgette-pilaf/",
    image:
      "https://www.bbcgoodfoodme.com/assets/legacy/recipe/recipe-image/2020/07/sausagecourgette-pilaf.jpg",
    imageAlt: "",
    title: "Sausage & courgette pilaf",
    time: "1 hr",
    description:
      "This sausage, courgette and rice dish is simple but full of flavour, and freezes well.",
    serves: 9,
    ingredients: [
      [3, " cups basmati rice"],
      [2, " tbsp vegetable oil"],
      [12, " sausages, meat squeezed from the skins"],
      [2, " tsp crushed coriander seeds"],
      [3, " courgettes, sliced into half-moons"],
      [700, "g frozen peas"],
      [3, " vegetable stock cubes"],
      [6.5, " cups water"],
      [2, " tsp dried mint"],
      [1, " tsp dried dill"],
      [2, " tbsp fat-free yogurt, optional"],
    ],
    method: [
      "Heat the oil in a large pan with a lid on a high heat and fry the courgette half-moons and coriander seeds for 5-15 mins until the courgettes go soft and slightly brown.",
      "Remove the courgettes from the pan and cook the sausage meat until crisp and golden.",
      "Put the courgettes back into the pan along with the rice, vegetable stock cubes, mint, dill and 6 cups of water.",
      "Bring to a simmer, then reduce the heat to low and cover with the lid.",
      "Cook for around 10 mins until the rice is tender, adding more water if required, then add the frozen peas and stir for a minute.",
      "Optionally serve with fresh herbs and yoghurt on the side.",
    ],
    filters: {
      details: {
        type: "main meal",
        base: "rice",
        protein: "sausage",
        dish: "pilaf",
        cookingMethod: ["hob"],
      },
      attributes: {
        freezable: true,
        hotWeatherFriendly: false,
        author: "",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: true,
        eggFree: true,
        halal: false,
        fishFree: true,
        glutenFree: false,
        kosher: false,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: false,
        vegetarian: false,
        vegan: false,
        veganAdjustable: false,
      },
    },
  },
  {
    path: "/sausage-leek-mash-pie",
    inspiredBy: "https://www.bbcgoodfood.com/recipes/sausage-leek-mash-pie",
    image:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/sausage-leek-mash-pie-07a67d4.jpg?quality=90&webp=true&resize=440,400",
    imageAlt:
      "Serving pot filled to the brim with cheesy mash, with a thick sausage and leek gravy peeking through below",
    title: "Sausage & leek mash pie",
    time: "1 hr 20",
    description:
      "Enjoy sausages and kale with a cheesy mash topping made with leeks and mustard. You can freeze this pie for busy weeknights when you need to feed a crowd",
    serves: 2,
    ingredients: [
      [4, " large potatoes, peeled and cut into 3cm chunks"],
      [2, " tbsp oil"],
      [6, " pork sausages"],
      [1, " tbsp plain flour"],
      [450, "ml fresh chicken gravy"],
      [150, "g kale, shredded"],
      [3, " leeks, finely sliced"],
      [0.5, " tbsp wholegrain mustard"],
      [2, " tbsp whole milk"],
      [50, "g smoked or ordinary cheddar, grated"],
    ],
    method: [
      "Boil the potatoes for 12 mins or until tender. Drain and leave to steam-dry.",
      "Heat 1 tbsp oil in a shallow casserole or deep skillet (20-25cm). Pinch the sausages out of their skins into large pieces, directly into the pan, and fry over a medium heat for 7-8 mins or until golden brown. Add the flour and stir everything together, cooking for 1 min. Pour in the gravy and 100-200ml water, bring to a simmer, then add the kale and cook for 5 mins. Remove from the heat.",
      "Meanwhile, in a separate pan, add the remaining 1 tbsp oil, then the leeks and fry for 5-10 mins until tender, adding a small splash of water to help them cook. Heat your grill to its highest setting.",
      "Mash the potatoes until smooth. Stir through the leeks, mustard and milk, and season. Spoon and swirl the mash on top of the sausage mixture, then scatter over the grated cheese and grill for 3-5 mins or until golden and bubbling.",
    ],
    filters: {
      details: {
        type: "main meal",
        base: "potato",
        protein: "sausage",
        dish: "pie",
        cookingMethod: ["hob", "grill"],
      },
      attributes: {
        freezable: true,
        hotWeatherFriendly: false,
        author: "",
      },
      dietaries: {
        dietaryNotes: "",
        dairyFree: false,
        eggFree: true,
        halal: false,
        fishFree: true,
        glutenFree: false,
        kosher: false,
        lactoseFree: false,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: false,
        vegetarian: false,
        vegan: false,
        veganAdjustable: false,
      },
    },
  },
  {
    path: "/vegan-choc-chip-cookie-squares",
    inspiredBy: "https://bakedbyclo.com/vegan-mini-egg-cookie-bars/",
    image: "https://tse4.mm.bing.net/th/id/OIP.TGz02e3VrwgeVD0g1UzX_wHaJQ?r=0&pid=Api",
    imageAlt: "Chewy vegan chocolate chip cookie squares baked in a tin",
    title: "Vegan choc chip cookie squares",
    time: "45 mins",
    description: "Chewy square-shaped choc chip cookies",
    serves: 12,
    ingredients: [
      [200, "g vegan margarine"],
      [150, "g caster sugar"],
      [100, "g soft brown sugar"],
      [1, " teaspoon vanilla extract"],
      [320, "g self-raising flour"],
      [250, "g vegan chocolate chips or vegan dark chocolate chopped up"],
      [0, " Splash plant-based milk"],
    ],
    method: [
      'Preheat your oven to 180°C/160°C Fan. Line an 8x10"/20x25cm tin with baking paper or wipe the tin with the vegan margarine. Letting some hang over the edges allows for easy removal.',
      "In a large bowl, mix together the margarine, caster sugar and brown sugar. Add in the vanilla and mix again.",
      "Next, add all of the flour to the bowl. Mix it in and when it starts to stick together, use your hands to press it into a dough. If the dough is crumbly, add a small splash of plant-based milk to help it stick together. I used about 2 teaspoons.",
      "Once your dough is the right consistency, add in the chocolate chips, saving a handful for the top. Gently fold them in using your hands.",
      "Place the cookie dough into your lined baking tin and press it out to the edges as evenly as you can. Gently press in the remaining chocolate chips.",
      "Bake for 25 minutes or until the top is light golden brown. Leave it in the tin to cool completely.",
      "Once cool, place it in the fridge for 2 hours. This will help it to firm up quicker and prevent the cookie squares from crumbling.",
      "After refrigerating, cut the cookie into 12 equal-sized squares and enjoy!",
    ],
    filters: {
      attributes: {
        author: "",
        freezable: true,
        hotWeatherFriendly: false,
      },
      details: {
        type: "baking",
      },
      dietaries: {
        dietaryNotes:
          "Ensure all chocolate chips and plant-based milk brands used are certified gluten-free/nut-free if catering for strict allergies.",
        dairyFree: true,
        eggFree: true,
        halal: true,
        fishFree: true,
        glutenFree: false,
        kosher: true,
        lactoseFree: true,
        nutFree: true,
        shellfishFree: true,
        soyFree: true,
        pescatarian: true,
        vegetarian: true,
        vegan: true,
      },
    },
  },
];

export const data = unsortedData.sort((a, b) => a.title.localeCompare(b.title));
